FROM python:3.9.9

WORKDIR /tests

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./tests/requirements.txt requirements.txt
ADD ./tests/run_tests.sh /
RUN chmod +x /run_tests.sh

RUN  pip install --no-cache-dir --upgrade pip \
     && pip install --no-cache-dir -r requirements.txt


COPY ./tests /tests/
